version: "3"
services:
  mysql: 
    image: mysql
    ports: ["3306:3306"]

    environment:
      - MYSQL_ROOT_PASSWORD=Sendmore1
      - MYSQL_DATABASE=moco
      - MYSQL_USER=username
      - MYSQL_PASSWORD=1qaz2wsx
  
  server:
    image: mobicon-server
    build:
      context: ./Mobicon
    ports: [80:80]
    environment:
      - MYSQL_CONNECTION_STRING="Server=localhost;Database=moco;Uid=username;Pwd=1qaz2wsx"