version: "3"
services:
  mysql: 
    image: mysql
    ports: ["3306:3306"]
    volumes:
      - "/opt/mobicon/db:/var/lib/mysql"

    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_HOST
  
  server:
    image: mobicon-server
    depends_on: [mysql]
    build:
      context: ./Mobicon
    ports: ["80:80"]
    environment:
      - MYSQL_CONNECTION_STRING
      - ASPNETCORE_ENVIRONMENT=Development
