version: "3"
services:
  mysql: 
    image: mysql
    ports: ["3306:3306"]

    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  
  server:
    image: mobicon-server
    build:
      context: ./Mobicon
    ports: [80:80]
    environment:
      - MYSQL_CONNECTION_STRING